### ISSUE TITLE
Question on .__lock file

### ISSUE THREAD

**Issue by dougbot01** [Preston-Landers/concurrent-log-handler#12]
Hi,

Sorry to put this as an issue, but I've been struggling to get TimedRotatingFileHandler working on Windows and your package appears to be the best solution I can find.

I'm using this handler for logging in a Flask web application, which is running in a gevent WSGI container. Quitting the application is just by a "ctrl-c" or if it's a Task Scheduler task there is just the "end task" option.

In either method, I have a file .__flask.lock left after the application is stopped.

Do I need to find a way to delete this file, or is it safe to leave it there?

Thank you!

**Comment by Preston-Landers** [comment]
It is safe to leave it there. Completely harmless. You can delete it if you like when the application is cleanly shut down. From within the concurrent-log-handler code, I don't think we have a reliable way of knowing when the app is safely shut down, especially on Windows. When you "End Task" it is equivalent to kill -9 which doesn't give the app a chance to run cleanup tasks.
