### ISSUE TITLE
Crashes on Python 3.5.3 64bit on Windows 10

### ISSUE THREAD

**Issue by nsmcan** [Preston-Landers/concurrent-log-handler#13]
Hello,

Not sure why was that idea to hard copy the portalocker module inside of the distributive?!

What I have:
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
concurrent_log_handler Version: 0.9.8 (just instaled)

Created a test file from your example on the home page: test.py.
Started it, got Windows dialog: Python has stopped working. 
Debugger shows some problem with code calling msvcr100.dll!_get_osfhandle(int fh)

Did: pip install -U portalocker
Changed in Lib\site-packages\concurrent_log_handler\__init__.py:
#from concurrent_log_handler.portalocker import LOCK_EX, LOCK_NB, LockException, lock, unlock
from portalocker import LOCK_EX, LOCK_NB, LockException, lock, unlock

Started test.py again. It worked fine.

I will do more tests and let you know if anything else failing.

**Comment by nsmcan** [comment]
OK, after testing with stresstest.py, I have found a cause of the problem and way to fix it. By the way, the similar way I have fixed the ConcurrentRotatingFileHandler module last year...

Sometimes, calling lock(self.stream_lock, LOCK_EX) could cause Resource deadlock avoided exception from portalocker. Not sure why does it happen more frequently with Python 3.5. I was not able to catch the same problem with Python 2.7. Most likely it relates to the different versions of the Microsoft DLLs used.

You emit() code catches this exception, skip writing, but tries to unlock file:

            finally:
                self._do_unlock()

Because it is not locked - process crashes there.

Initially I used the self.islocked property to track that. That helped to avoid crashes. But having some logs missing because of the deadlock exceptions is not good. So here is my solution:

`...`
`#from concurrent_log_handler.portalocker import LOCK_EX, LOCK_NB, LockException, lock, unlock`
`from portalocker import LOCK_EX, LOCK_NB, LockException, lock, unlock`
`...`

    def __init__(self, filename, mode='a', maxBytes=0, backupCount=0,
                 encoding=None, debug=False, delay=0, use_gzip=False,
                 owner=None, chmod=None, umask=None):
        ...
        self.islocked = False

    def _do_lock(self):
        self._open_lockfile()
        if self.stream_lock:
            lock(self.stream_lock, LOCK_EX)
            for i in range(10):
                try:
                    lock(self.stream_lock, LOCK_EX)
                    self.islocked = True
                    break
                except:
                    continue
            else:
                raise RuntimeError("Cannot acquire lock after 10 attempts")
       else:
            self._console_log("No self.stream_lock to lock", stack=True)
 
    def _do_unlock(self):
        if self.stream_lock:
            if self.islocked:
                unlock(self.stream_lock)
                self.islocked = False
            self.stream_lock.close()
            self.stream_lock = None
        else:
            self._console_log("No self.stream_lock to unlock", stack=True)

With that and with the latest portalocker - it works in Python 3.5 64 bits!

**Comment by Preston-Landers** [comment]
Thanks for the report. I'll have to do some investigation.

I have been successfully using this module with Python 3.6.2 (x64) on Windows 10 for some time. I have not really done any testing with Python 3.5.

As far as why it includes its own copy of portalocker, it's because my first version of this used an independent fork of it that had already been in use for some time in another project of mine. I think I checked  and found some small but potentially important differences. Since then I haven't taken the time to iron out the differences and switch to that other distribution. I didn't have a good incentive given that it was working fine for me but that can be revisited.

**Comment by Preston-Landers** [comment]
Hi @nsmcan , please try out concurrent-log-handler 0.9.13 and see if that helps things. If it's still crashing with that new version please feel free to reopen this issue.
