### ISSUE TITLE
use_gzip does not compress nor rename on Windows

### ISSUE THREAD

**Issue by GoranGoranovic** [Preston-Landers/concurrent-log-handler#17]
My current environment:
```
C:\..>python -V
Python 3.7.0

C:\..>VER

Microsoft Windows [Version 10.0.16299.785]

C:\..>pip list
Package                Version
---------------------- ----------
certifi                2018.10.15
chardet                3.0.4
concurrent-log-handler 0.9.12
cycler                 0.10.0
docopt                 0.6.2
idna                   2.7
kiwisolver             1.0.1
matplotlib             3.0.0
numpy                  1.15.2
pandas                 0.23.4
pip                    18.1
pipreqs                0.4.9
psutil                 5.4.7
pyaml                  17.12.1
pyparsing              2.2.1
pypiwin32              223
python-dateutil        2.7.3
pytz                   2018.5
pywin32                224
PyYAML                 3.13
requests               2.20.0
setuptools             39.0.1
six                    1.11.0
urllib3                1.24
yarg                   0.1.9

>pip -V
pip 18.1 from c:\..\scoop\apps\python\current\lib\site-packages\pip (python 3.7)
```

Basically I am stumped why the files are not being gzip compressed when rolled over?
And renaming (post fix .gz) never happens either ... but that's probably the same issue. 

Rolling over while running with multiprocessing is working just fine, The only thing that is not working ... is gzip compression.

Any ideas or should I just try running is on a Linux instance?  :)
Thank you ahead of time.

Goran

**Comment by Preston-Landers** [comment]
Hmm... it looks like it's working for me on Windows. A couple of things to check:

1) Can you `import gzip` in your Python interpreter?

2) Try setting the `debug=True` option on the log handler.  The output would go to stdout, not the log. If it says "no gzip available" then it ran into problems importing gzip.

**Comment by Preston-Landers** [comment]
@GoranGoranovic were you able to have any luck this? There is a new version to try 0.9.13 also.

**Comment by Preston-Landers** [comment]
Unable to reproduce and no additional details were provided. You can reopen this if you can reproduce with the newest release.
