### ISSUE TITLE
On Windows, logs with encoding are written with Unix ends-of-line (LF instead of CRLF)

### ISSUE THREAD

**Issue by vashek** [Preston-Landers/concurrent-log-handler#19]
If I specify an encoding, the log file is opened in binary mode, which on Windows causes it to be written with Unix-style line endings.
I may be missing something, but I can't figure out why the file is being opened via codecs.open instead of the simple open. The pull request I opened fixes this by simply always using open. I can't think of why it wasn't done like this in the first place.

**Comment by Preston-Landers** [comment]
It looks like `io.open()` is the way to go to support Python 2.6 through 3.x with the encoding parameter. I'm doing some testing now.

**Comment by Preston-Landers** [comment]
Version 0.9.14 should take care of this, hopefully. Thanks for the bug report!
