### ISSUE TITLE
using globally from a single module

### ISSUE THREAD

**Issue by rootVIII** [Preston-Landers/concurrent-log-handler#22]
Is there a preferred way to globally implement your example code from within a single .py file/module, and import it into the other modules of a larger sized project? Other than the .ini file?
EDIT: Nevermind I ended up sticking with the .ini file.  Runs nicely thanks

**Comment by Preston-Landers** [comment]
Yeah, the critical elements are, in order:

1. You must `import concurrent_log_handler` somewhere, which registers the handler with Python logging as a side effect. 

2. You must tell Python logging to use concurrent_log_handler and where to put the output files. You can do this via an `.ini` file then calling `logging.config.fileConfig(filename)` or directly passing a configuration dict with `logging.config.dictConfig`. There are other ways too. 

Generally, you would want to do the above steps somewhere early in your application startup script. You can also do it in the Python site specific config hook: https://docs.python.org/3/library/site.html

Using sitecustomize.py has the nice effect of ensuring your logging config is used from all prompts and related scripts, not just your main application program.

**Comment by rootVIII** [comment]
Gotcha... Thank you
