### ISSUE TITLE
ImportError: No module named win32con

### ISSUE THREAD

**Issue by evandrocoan** [Preston-Landers/concurrent-log-handler#3]
I was just trying to use this on AppVeyor with Python 2.7 but its fails with this:
```python
Traceback (most recent call last):
  File "c:\projects\python-language-server\.tox\py27\lib\site-packages\_pytest\config.py", line 365, in _importconftest
    mod = conftestpath.pyimport()
  File "c:\projects\python-language-server\.tox\py27\lib\site-packages\py\_path\local.py", line 668, in pyimport
    __import__(modname)
  File "c:\projects\python-language-server\.tox\py27\lib\site-packages\_pytest\assertion\rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "c:\projects\python-language-server\.tox\py27\lib\site-packages\py\_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "C:\projects\python-language-server\test\conftest.py", line 4, in <module>
    from pyls.__main__ import LOG_FORMAT
  File "C:\projects\python-language-server\pyls\__main__.py", line 8, in <module>
    from concurrent_log_handler import ConcurrentRotatingFileHandler
  File "c:\projects\python-language-server\.tox\py27\lib\site-packages\concurrent_log_handler\__init__.py", line 61, in <module>
    from concurrent_log_handler.portalocker import lock, unlock, LOCK_EX, LOCK_NB, LockException
  File "c:\projects\python-language-server\.tox\py27\lib\site-packages\concurrent_log_handler\portalocker.py", line 89, in <module>
    import win32con
ImportError: No module named win32con
ERROR: could not load C:\projects\python-language-server\test\conftest.py
```
1. https://github.com/palantir/python-language-server/pull/254
1. https://ci.appveyor.com/project/gatesn/python-language-server/build/1.0.375/job/ln3alujea5t1e329

**Comment by Preston-Landers** [comment]
Thanks for the report. I think the problem is that you need to install PyWin32. 

This could be handled better, but the readme does say "PyWin32 is required on Windows, but can't be installed as an automatic dependency because it's not currently installable through pip."

I think the very latest version of PyWin32 that was just released actually fixes this issue (unable to be listed as a normal pip dependency) so maybe this problem can be fixed that way.

**Comment by evandrocoan** [comment]
I had it working on Python 2 by adding to install these dependencies:
```
    pywin32
    pypiwin32
```

But `tox` is failing when running on Python 3 because `pywin32` it is already built-in on it: 

1. https://github.com/tox-dev/tox/issues/758 How to not install Python 2 dependencies on Python 3?

I am not sure if you can include these as dependencies here because they should fail to install when running Python 3.

**Comment by Preston-Landers** [comment]
It should be possible to create a dependency that only applies to Python 2. I did it once but I'll have to go back and find it.

I thought `pypiwin32` was a compatibility wrapper that was no longer needed with the latest PyWin32 version 222. I'll look into it.

**Comment by evandrocoan** [comment]
I just find a complete answer: https://stackoverflow.com/questions/19672980/can-you-set-conditional-dependencies-for-python-2-and-3-in-setuptools

**Comment by evandrocoan** [comment]
I just happened to add `pypiwin32` to setup.py and it worked for Python 2 and 3, can you add it as dependency for this package?

```
    install_requires=[
        ...
        'pypiwin32',
        ...
    ],
```

1. https://ci.appveyor.com/project/gatesn/python-language-server/build/1.0.389

**Comment by Preston-Landers** [comment]
I will investigate how the prerequisites are handled, yes. Thanks for the report.

**Comment by Preston-Landers** [comment]
See this issue: https://github.com/mhammond/pywin32/issues/1151

There may be an issue with how PyWin32 release 222 handles certain things when installed through pip. I may have to hold off on changing anything here until I see how a new PyWin32 handles it. 

For now the workaround should be to install PyWin32 manually or through pip and `pypiwin32`.
