### ISSUE TITLE
Installation issue on Windows for python 3.8 when no internet access is given

### ISSUE THREAD

**Issue by blackgis** [Preston-Landers/concurrent-log-handler#33]
`\python38\lib\site-packages\pip\_vendor\requests\utils.py", line 74, in proxy_bypass_registry

    proxyOverride = proxyOverride.split(';')

AttributeError: 'list' object has no attribute 'split'`

I found out that the installer is missing a warning that checks prior if portalocker and pywin32 228 is installed. When i have installed these, it works fine to install current_log_handler. 
The error arrised because i have no internet connection where i needed this, on my normal workstation i realized that the other 2  wheels got downloaded automatically from the internet and needed to be installed before the current log handler can be installed.

**Comment by Preston-Landers** [comment]
Have you installed PyWin32 outside of pip? 

The Concurrent-log-handler (CLH) setup.py only adds a pywin32 install dependency if it can't import win32file. However, it always adds a portalocker dependency, and portalocker itself depends on pywin32. 

I'm not certain yet this is a bug in CLH (it might be). We could potentially put a workaround in to check for portalocker availability before declaring it a dependency, but I'd prefer to understand exactly what's happening first. 

Pip does have some command line options that might help.  Also setting environment vars to disable proxy usage might help.
```
set https_proxy=
set http_proxy=
pip --no-index --no-cache-dir -f $(PACKAGE_DIR) install -r requirements.txt
```
You could pre-download packages to a dir given above as $(PACKAGE_DIR). Then it would work offline.

**Comment by Preston-Landers** [comment]
Closed pending further data.
