### ISSUE TITLE
Wheel is not really universal

### ISSUE THREAD

**Issue by buddly27** [Preston-Landers/concurrent-log-handler#36]
The following condition is not properly transmitted into the wheel:
```python
try:
    IS_PY2 = sys.version_info.major == 2
except Exception:
    IS_PY2 = True

if IS_PY2:
    # https://github.com/Preston-Landers/concurrent-log-handler/issues/28
    # If Python 2, don't allow fulfillment with portalocker 2.0 as it won't work
    install_requires = ['portalocker<=1.7.1']
else:
    install_requires = ['portalocker>=1.4.0']
```

Therefore, if the wheel is creating with Python 3.8, the installation will require 'portalocker>=1.4.0', even if the targeted Python version in 2.7. Using conditional dependency as defined in [PEP-508](https://www.python.org/dev/peps/pep-0508/) will make the wheel truly [universal](https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels):

```python
install_requires = [
    'portalocker<=1.7.1; python_version < "3"',
    'portalocker>=1.4.0; python_version >= "3"',
]
```

The wheel currently uploaded to PyPi is not working on 2.7 for this reason:
https://pypi.org/project/concurrent-log-handler/#files

**Comment by buddly27** [comment]
Maybe it would be worth adding an upper boundary to 'portalocker' on Python 3 To prevent issue in case of API break?

```python
install_requires = [
    'portalocker<=1.7.1; python_version < "3"',
    'portalocker>=1.4.0, <3; python_version >= "3"',
]
```

**Comment by Preston-Landers** [comment]
Thanks for the PR!
