### ISSUE TITLE
Unable to set user or group to root

### ISSUE THREAD

**Issue by GauthamAnil** [Preston-Landers/concurrent-log-handler#42]
https://github.com/Preston-Landers/concurrent-log-handler/blob/75f1ae2ba1ccd5064eefa66e0f58d7a6fb497b87/src/concurrent_log_handler/__init__.py#L564

This should check for None. 0 is a valid user or group id (root, root)

**Comment by Preston-Landers** [comment]
OK, I'll take a look at updating that when I can. Thanks for the report.

**Comment by Preston-Landers** [comment]
@GauthamAnil - this should now be fixed in version 0.9.20. You can reopen if it doesn't work for you.  Thanks.
