### ISSUE TITLE
Question:-Does it support on python 3.9 or higher ?

### ISSUE THREAD

**Issue by onkar6699** [Preston-Landers/concurrent-log-handler#43]

**Comment by Preston-Landers** [comment]
Yes it does, but the docs haven't been updated to indicate that yet.

**Comment by onkar6699** [comment]
@Preston-Landers okay Thanks you !

**Comment by onkar6699** [comment]
@Preston-Landers  please update it. thanks

**Comment by onkar6699** [comment]
@Preston-Landers have you also not updated pip concurrent_log_handler package?

**Comment by onkar6699** [comment]
@Preston-Landers  Thanks for the update.
