### ISSUE TITLE
Additional parameter for alternative lock file directory

### ISSUE THREAD

**Issue by aDramaQueen** [Preston-Landers/concurrent-log-handler#49]
Hi,
not an Issue, more a proposal. Would it be possible to add an additional parameter, to determine the target directory for the lock files?

In our current setup, we use Gunicorn for our Django websites. Since Gunicorn spawns multiple workers, we are in the exact situation to use this fine piece of software you guys offering here.

Now the special case: I want to dockerize the whole applicatin chain. NGINX, Gunicorn, Django, Databases...
The problem now, is that I want to share the logs, within a docker compose system. Therefore, I have to create a volume with the logging directory.

Problem now, since the lock files live directly next to the logging files, the locks get shared as well. This, by it self is not really a problem. **BUT** it slows the whole process down. Since it needs time, for Docker to copy these files into each other volume to prevent the state from inconsistencies.

And here the proposal: Lets move the lock files away from the logging files, that we can now share these files and don't suffer from the Docker latency penalties.

Thank you

**Comment by Preston-Landers** [comment]
Yeah, I believe at least one other person has requested this, though I don't think they opened an issue. I think it does make sense.

I'm super busy and moving over the next month, but feel free to work up a pull request, or I'll get to it when I can. Thanks.

**Comment by aDramaQueen** [comment]
Alrighty then,

created already a pull request.

Thanks
