### ISSUE TITLE
Does not build with Python 3.11

### ISSUE THREAD

**Issue by StefanTT** [Preston-Landers/concurrent-log-handler#58]
```
  parsed = self.parsers.get(option_name, lambda x: x)(value)
/usr/lib/python3.11/site-packages/setuptools/dist.py:954: DistDeprecationWarning: use_2to3 is ignored.
  ep.load()(self, ep.name, value)
error in concurrent-log-handler setup command: use_2to3 is invalid.
```

Removing `use_2to3` in setup.py fixes it.

**Comment by Preston-Landers** [comment]
That's weird because I've been using Python 3.11.2 recently to work on it. And the GH Actions are [working under Python 3.11](https://github.com/Preston-Landers/concurrent-log-handler/actions/runs/4845851419/jobs/8635015270). I do see the deprecation warning and agree it should be cleaned up, but it's not a fatal error for me. Actually there's another deprecation about `license_file`.

Are you running this as part of a larger build process that's set to make those deprecation warnings fatal? Are you not wanting to use the wheel file on pypi?

My env:

```sh
setuptools             65.6.3

>python --version
Python 3.11.2

(venv) C:\dev\concurrent-log-handler>python setup.py clean --all build
C:\dev\concurrent-log-handler\venv\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
C:\dev\concurrent-log-handler\venv\Lib\site-packages\setuptools\dist.py:316: DistDeprecationWarning: use_2to3 is ignored.
  warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
running clean
removing 'build\lib' (and everything under it)
'build\bdist.win-amd64' does not exist -- can't clean it
'build\scripts-3.11' does not exist -- can't clean it
removing 'build'
running build
running build_py
creating build
creating build\lib
creating build\lib\concurrent_log_handler
copying src\concurrent_log_handler\queue.py -> build\lib\concurrent_log_handler
copying src\concurrent_log_handler\__init__.py -> build\lib\concurrent_log_handler
copying src\concurrent_log_handler\__version__.py -> build\lib\concurrent_log_handler

```

**Comment by StefanTT** [comment]
```
$ pacman -Qi python-setuptools
Name            : python-setuptools
Version         : 1:67.7.0-1

$ python --version
Python 3.11.3

$ python setup.py clean --all build
/usr/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
!!
        ********************************************************************************
        The license_file parameter is deprecated, use license_files instead.
        [...]
!!
  parsed = self.parsers.get(option_name, lambda x: x)(value)
/usr/lib/python3.11/site-packages/setuptools/dist.py:954: DistDeprecationWarning: use_2to3 is ignored.
  ep.load()(self, ep.name, value)
error in concurrent-log-handler setup command: use_2to3 is invalid.

**Comment by Preston-Landers** [comment]
I don't necessarily recommend downgrading setuptools. I should be able to publish a new release soon-ish that fixes it. The wheel file isn't an option for you?

**Comment by StefanTT** [comment]
When it comes to Python I am rather a user of the packages that others provide (for Arch Linux in my case). The build file for the concurrent-log-handler only pulls `python-setuptools` and then starts the build. 

I am by no means hindered by this problem, I only wanted to report it. So please do not rush to fix it. Thank you for your help nevertheless!

**Comment by AtomicFS** [comment]
Hi there, I have encountered the same exact problem, using Arch Linux and pacman package manager to handle the installation.

Maybe a side-note, please do not take this the wrong way, but I am one of those people who do not believe that each language should come with it's own package manager and package system (be it Python, Rust, ...). This is unfortunately the trend lately.

**Comment by Preston-Landers** [comment]
Release 0.9.24 was just published and should hopefully fix this.
