### ISSUE TITLE
ConcurrentTimedRotatingFileHandler deprecated delay warning

### ISSUE THREAD

**Issue by platinops** [Preston-Landers/concurrent-log-handler#60]
When the `ConcurrentTimedRotatingFileHandler `is used without specifying the `delay` parameter, the following warning is shown:

> DeprecationWarning: concurrent_log_handler parameter `delay` is now ignored and implied as True, please remove from your config.

This seems to be due to the [default value of False](https://github.com/Preston-Landers/concurrent-log-handler/blob/3a589de62608ad8e56023fd86d8364a2ef5bc2bb/src/concurrent_log_handler/__init__.py#L621), while it is [None](https://github.com/Preston-Landers/concurrent-log-handler/blob/3a589de62608ad8e56023fd86d8364a2ef5bc2bb/src/concurrent_log_handler/__init__.py#LL121C15-L121C15)  for `ConcurrentRotatingFileHandler`.

I'm guessing either the default value should change, or [this check ](https://github.com/Preston-Landers/concurrent-log-handler/blob/3a589de62608ad8e56023fd86d8364a2ef5bc2bb/src/concurrent_log_handler/__init__.py#L216)should be `(None, False)`:

``` python
if delay not in (None, True):
    warnings.warn(
        "concurrent_log_handler parameter `delay` is now ignored and implied as True, "
        "please remove from your config.",
        DeprecationWarning,
        stacklevel=3,
    )
```

**Comment by Preston-Landers** [comment]
Fixed in master branch; I may wait a little bit before putting out a new release. Thanks for the report.
