### ISSUE TITLE
Broken and blank lines produced in logging with multiprocessing example

### ISSUE THREAD

**Issue by Krogsager** [Preston-Landers/concurrent-log-handler#62]
Hi, I'm unable to get any logging written to either file nor console when using multiprocessing Pool or Process .start()/.join().
Can anyone provide an example?
My logs work fine when running multiple threads. I did call setup_logging_queues() but I'm not sure where to place it.

Working:
```python
from src.concurrent_logger import log
import threading
import time

def thread_function(thread_id):
    log.info(f"Thread {thread_id} started")
    time.sleep(0.01)  # Simulating some work
    log.info(f"Thread {thread_id} finished")

if __name__ == "__main__":
    threads = []
    for i in range(1, 100):
        thread = threading.Thread(target=thread_function, args=(i,))
        threads.append(thread)
        thread.start()

    # Wait for all threads to finish
    for thread in threads:
        thread.join()
```
Not working:
```python
from src.concurrent_logger import log
import multiprocessing
import time

def thread_function(thread_id):
    log.info(f"Thread {thread_id} started")
    time.sleep(0.01)  # Simulating some work
    log.info(f"Thread {thread_id} finished")


if __name__ == "__main__":
    processes = []
    for i in range(1, 11):
        process = multiprocessing.Process(target=thread_function, args=(i,))
        processes.append(process)
        process.start()

    # Wait for all processes to finish
    for process in processes:
        process.join()
```
I placed concurrent_log_handler.queue.setup_logging_queues() in the log setup. It produces a seemingly random number (between 3 and 10 maybe) of log lines saying
> 13-07-2023 11:30:25.620 -[proactor_events.py:633] - DEBUG - Using proactor: IocpProactor

If I don't call setup_logging_queues()  at all, then no output is produced.

**Comment by Preston-Landers** [comment]
The README tries to explain this, though it doesn't do a great job of it. When using `multiprocessing`, each child process must initialize Concurrent-Log-Handler object as if it's the master process. It doesn't transfer automatically from parent to child under multiprocessing. That step isn't necessary when using threading or `fork()`. 

In effect, your `thread_function()` in the example must call your logging setup code. It looks like your logging setup code happens on this line: `from src.concurrent_logger import log`. It might be sufficient to move that import statement into the body of `thread_function`. 

In the file [src/example.py](https://github.com/Preston-Landers/concurrent-log-handler/blob/master/src/example.py) there's a setup function `my_logging_setup`. You'd have to call something like that in each multiprocessing child.

This is also shown (somewhat indirectly) in the multiprocessing based [unit test stresstest.py](https://github.com/Preston-Landers/concurrent-log-handler/blob/master/tests/stresstest.py). The child process runs the function `worker_process`, which makes its own CLH object and calls `addHandler` directly.

**Comment by Krogsager** [comment]
Indeed yes, it worked to import log within `thread_function()`! It does not look very pythonic, but I'm a lazy man, and will leave it there.
For the sake of verbosity, here is the "final" code
```python
from src.concurrent_logger import log
import multiprocessing
import time

def thread_function(thread_id):
    from src.concurrent_logger import log
    log.info(f"Thread {thread_id} started")
    for x in range(50):
        log.info(f"Thread {thread_id} writing line {x}")


if __name__ == "__main__":
    start = time.time()
    processes = []
    for i in range(1, 30):
        process = multiprocessing.Process(target=thread_function, args=(i,))
        processes.append(process)
        process.start()

    # Wait for all processes to finish
    for process in processes:
        process.join()

    log.info(f"runtime {time.time()-start}")
```

When I stress the system I'm now encountering glitches in the log. Broken lines and empty lines. I'm happy to share the full code if this is unexpected:
![image](https://github.com/Preston-Landers/concurrent-log-handler/assets/27994384/0e835c42-12d7-4cb4-8a28-1a1c54a57331)
This happens regardless of setup_logging_queues()

**Comment by Preston-Landers** [comment]
Hmm, yes, I would say it's unexpected. There is a unit test which does a multiprocessing-based stress test, and then checks for things like broken lines.

I wonder what happens if you run those tests, or possibly an altered version of them (e.g. more processes, longer runtime, etc), in your environment. Or if we can find some other way to replicate it in the tests.

To run the tests you can clone the repo and follow the [developer setup](https://github.com/Preston-Landers/concurrent-log-handler#developer-setup). The various test cases / options are defined in `tests/test_stresstest.py`.

**Comment by Krogsager** [comment]
Unsurprisingly the unittests run fine by default. I took a look at the code, but couldn't see an obvious way to make them run like my code. So I have nothing to show for the effort.

**Comment by Preston-Landers** [comment]
So the code you're running that produces the broken lines is basically just that short block of code from your previous comment? 

I see the `proactor_events` stuff - is it possible that something is writing to the same log file without going through CLH?

CLH just uses an advisory lock (via portalocker), which means there is no actual protection from some random process opening and writing to the file in the middle of your logging, whether Python or anything else.

**Comment by Krogsager** [comment]
Sure!
I've hardcoded the config from the TOML so you don't need to create it yourself.
```python
# concurrent_logger.py
import logging
from concurrent_log_handler import ConcurrentRotatingFileHandler
from concurrent_log_handler.queue import setup_logging_queues
import tomllib
import os

#toml_path = os.path.join(
#    os.path.dirname(os.path.abspath(__file__)),
#    "config.toml")
#
#with open(toml_path,'rb') as f:
#    config = tomllib.load(f)
#log_config = config['logging']['config']

log_config = dict(level='DEBUG',
                    filename='concurrent.log',
                    format='%(asctime)s.%(msecs)03d -[%(filename)s:%(lineno)d] - %(levelname)s - %(message)s',
                    datefmt='%d-%m-%Y %H:%M:%S',
                    style='%',)

logging.basicConfig(**log_config)
log = logging.getLogger()
# Use an absolute path to prevent file rotation trouble.
# Rotate log after reaching 512K, keep 5 old copies.

#rotateHandler = ConcurrentRotatingFileHandler(log_config['filename'], "a", 512 * 1024, 5)
rotateHandler = ConcurrentRotatingFileHandler('concurrent.log', "a", 512 * 1024, 5)

#if config['logging']['options']['log_to_console'] == True:3
if True:
    sh = logging.StreamHandler()
    # create stream handler so log messages are written to console
    sh.setFormatter(log.handlers[0].formatter) # reuse settings rather than creating Formatter object.
    log.addHandler(sh)

# To enable background logging queue, call this near the end of your logging setup.
setup_logging_queues()
```

**Comment by Krogsager** [comment]
TL:DR
Apparently File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\site-packages\concurrent_log_handler\queue.py", gives error RuntimeError: cannot release un-acquired lock


After rerunning this code https://github.com/Preston-Landers/concurrent-log-handler/issues/62#issuecomment-1640128113 I just discovered fragments of an error in my console: 

<details><summary>scrambled log dump</summary><p>

```bash
18-08-2023 09:19:46.373 -[temp.py:9] - INFO - Thread 17 writing line 49
18-08-2023 09:19:46.481 -[proactor_events.py:633] - DEBUG - Using proactor: IocpProactor
18-08-2023 09:19:46.483 -[proactor_events.py:633] - DEBUG - Using proactor: IocpProactor
Exception in thread Thread-1 (_monitor):
Traceback (most recent call last):
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\site-packages\concurrent_log_handler\queue.py", line 46, in _monitor
    super()._monitor()
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\handlers.py", line 1584, in _monitor
    self.handle(record)
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\handlers.py", line 1565, in handle
18-08-2023 09:19:46.486 -[proactor_events.py:633] - DEBUG - Using proactor: IocpProactor
    handler.handle(record)
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\__init__.py", line 980, in handle
18-08-2023 09:19:46.486 -[temp.py:7] - INFO - Thread 24 started
18-08-2023 09:19:46.486 -[temp.py:9] - INFO - Thread 24 writing line 0
18-08-2023 09:19:46.486 -[temp.py:9] - INFO - Thread 24 writing line 1
18-08-2023 09:19:46.486 -[temp.py:9] - INFO - Thread 24 writing line 2
18-08-2023 09:19:46.486 -[temp.py:9] - INFO - Thread 24 writing line 3
18-08-2023 09:19:46.486 -[temp.py:9] - INFO - Thread 24 writing line 4
18-08-2023 09:19:46.486 -[temp.py:9] - INFO - Thread 24 writing line 5
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 6
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 7
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 8
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 9
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 10
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 11
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 12
    self.release()
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 13
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\__init__.py", line 934, in release
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 14
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 15
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 16
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 17
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 18
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 19
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 20
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 21
18-08-2023 09:19:46.487 -[temp.py:9] - INFO - Thread 24 writing line 22
18-08-2023 09:19:46.488 -[temp.py:9] - INFO - Thread 24 writing line 23
18-08-2023 09:19:46.488 -[temp.py:9] - INFO - Thread 24 writing line 24
18-08-2023 09:19:46.488 -[temp.py:9] - INFO - Thread 24 writing line 25
18-08-2023 09:19:46.488 -[temp.py:9] - INFO - Thread 24 writing line 26
    self.lock.release()
18-08-2023 09:19:46.488 -[temp.py:9] - INFO - Thread 24 writing line 27
RuntimeError: 18-08-2023 09:19:46.488 -[temp.py:9] - INFO - Thread 24 writing line 28
cannot release un-acquired lock
18-08-2023 09:19:46.488 -[temp.py:9] - INFO - Thread 24 writing line 29
18-08-2023 09:19:46.488 -[temp.py:9] - INFO - Thread 24 writing line 30
```

</p></details>


Shortly after I got a more coherent log entry:
<details><summary>better log dump</summary><p>

```bash
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\__init__.py", line 1114, in emit
    self.flush()
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\__init__.py", line 1096, in flush
    self.release()
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\__init__.py", line 934, in release
    self.lock.release()
RuntimeError: cannot release un-acquired lock
Call stack:
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\site-packages\concurrent_log_handler\queue.py", line 46, in _monitor
    super()._monitor()
Message: 'Using proactor: IocpProactor'
Arguments: None
Exception in thread Thread-1 (_monitor):
Traceback (most recent call last):
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\site-packages\concurrent_log_handler\queue.py", line 46, in _monitor
    super()._monitor()
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\handlers.py", line 1584, in _monitor
    self.handle(record)
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\handlers.py", line 1565, in handle
    handler.handle(record)
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\__init__.py", line 980, in handle
    self.release()
  File "C:\Users\az27355\Anaconda3\envs\fosa\Lib\logging\__init__.py", line 934, in release
    self.lock.release()
RuntimeError: cannot release un-acquired lock
```

**Comment by Preston-Landers** [comment]
Well, the good news is that I was able to reproduce it. I don't have much time to dig into the details right now, and I can't promise a resolution date or anything, but it should be fixable, and I am curious what could be causing this.

**Comment by Preston-Landers** [comment]
Hi, sorry it took so long to respond, but I think I have an answer.

It comes down to how you're configuring the Python logging system. In the example code you provided, it's not actually using Concurrent Log Handler to emit the log messages to the file, it's just using the regular (non-concurrent) `FileHandler`. I confirmed this in a debugger. Therefore, the broken lines here are an example of why you might want to use CLH in the first place. 

Here's some updated code that properly configures the logging system to use CLH. Feel free to play around with it further. When I ran this code the log file had no broken / partial lines. 

```python
# app.py
import multiprocessing
import os
import time
from log_setup import setup_logging


def thread_function(thread_id):
    # setup_logging returns a `log` object, but as long as you call setup_logging
    # once in each process, you can make a new logger anywhere needed via logging.getLogger()
    log = setup_logging()

    log.info(f"Thread {thread_id} started")
    for x in range(50):
        log.info(f"Thread {thread_id} writing line {x}")


if __name__ == "__main__":
    if os.path.exists("concurrent.log"):
        os.remove("concurrent.log")

    log = setup_logging()

    start = time.time()
    processes = []
    for i in range(1, 30):
        process = multiprocessing.Process(target=thread_function, args=(i,))
        processes.append(process)
        process.start()

    # Wait for all processes to finish
    for process in processes:
        process.join()

    log.info(f"runtime {time.time()-start}")
```

```python
# log_setup.py
import logging
from logging.config import dictConfig

# Disable warning about unused import
from concurrent_log_handler import ConcurrentRotatingFileHandler  # noqa: F401
from concurrent_log_handler.queue import setup_logging_queues


def setup_logging():
    logging_config = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "example2": {
                "format": "%(asctime)s.%(msecs)03d -[%(filename)s:%(lineno)d] - %(levelname)s - %(message)s",
            },
        },
        # Set up our concurrent logger handler. Need one of these per unique file.
        "handlers": {
            "my_concurrent_log": {
                "level": "DEBUG",
                "class": "concurrent_log_handler.ConcurrentRotatingFileHandler",
                # Example of a custom format for this log.
                "formatter": "example2",
                "filename": "concurrent.log",
                # Number of rollover files to keep
                "backupCount": 10,
                # 'use_gzip': True,
            }
        },
        # Tell root logger to use our concurrent handler
        "root": {
            "handlers": ["my_concurrent_log"],
            "level": "DEBUG",
        },
    }

    dictConfig(logging_config)
    log = logging.getLogger()

    use_console = True
    if use_console:
        sh = logging.StreamHandler()
        # create stream handler so log messages are written to console
        # reuse settings rather than creating Formatter object.
        sh.setFormatter(log.handlers[0].formatter)
        log.addHandler(sh)

    # To enable background logging queue, call this near the end of your logging setup.
    setup_logging_queues()

    # We return a `log` object here, but as long as you call setup_logging
    # once in each process, you can make a new logger anywhere needed via logging.getLogger()
    return log

```

**Comment by Krogsager** [comment]
bravo! Thank you Preston.

**Comment by mirrornight** [comment]
> The README tries to explain this, though it doesn't do a great job of it. When using `multiprocessing`, each child process must initialize Concurrent-Log-Handler object as if it's the master process. It doesn't transfer automatically from parent to child under multiprocessing. That step isn't necessary when using threading or `fork()`.
> 
> In effect, your `thread_function()` in the example must call your logging setup code. It looks like your logging setup code happens on this line: `from src.concurrent_logger import log`. It might be sufficient to move that import statement into the body of `thread_function`.
> 
> In the file [src/example.py](https://github.com/Preston-Landers/concurrent-log-handler/blob/master/src/example.py) there's a setup function `my_logging_setup`. You'd have to call something like that in each multiprocessing child.
> 
> This is also shown (somewhat indirectly) in the multiprocessing based [unit test stresstest.py](https://github.com/Preston-Landers/concurrent-log-handler/blob/master/tests/stresstest.py). The child process runs the function `worker_process`, which makes its own CLH object and calls `addHandler` directly.

I'm a little confused about the subprocess calling my_logging_setup. so I modified the code, It seems that there is no need to call in the subprocess. When the child process executes import, a new log object is created.

`# log_setup.py
import logging
from logging.config import dictConfig
from concurrent_log_handler import ConcurrentRotatingFileHandler  # noqa: F401


logging_config = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "example2": {
            "format": "%(asctime)s.%(msecs)03d -[%(filename)s:%(lineno)d] - %(levelname)s - %(message)s",
        },
    },
    # Set up our concurrent logger handler. Need one of these per unique file.
    "handlers": {
        "my_concurrent_log": {
            "level": "DEBUG",
            "class": "concurrent_log_handler.ConcurrentRotatingFileHandler",
            # Example of a custom format for this log.
            "formatter": "example2",
            "filename": "concurrent.log",
            # Number of rollover files to keep
            "backupCount": 10,
            # 'use_gzip': True,
        }
    },
    # Tell root logger to use our concurrent handler
    "root": {
        "handlers": ["my_concurrent_log"],
        "level": "DEBUG",
    },
}

dictConfig(logging_config)
log = logging.getLogger()

use_console = True
if use_console:
    sh = logging.StreamHandler()
    # create stream handler so log messages are written to console
    # reuse settings rather than creating Formatter object.
    sh.setFormatter(log.handlers[0].formatter)
    log.addHandler(sh)`

`import multiprocessing
import os
import time
from log_setup import log


def thread_function(thread_id):
    log.info(f"Thread {thread_id} started, id: {id(log)}")
    for x in range(50):
        log.info(f"Thread {thread_id} writing line {x}")


if __name__ == "__main__":
    if os.path.exists("concurrent.log"):
        os.remove("concurrent.log")

    start = time.time()
    processes = []
    for i in range(1, 30):
        process = multiprocessing.Process(target=thread_function, args=(i,))
        processes.append(process)
        process.start()

    # Wait for all processes to finish
    for process in processes:
        process.join()

    log.info(f"runtime {time.time()-start}")`
