### ISSUE TITLE
ConcurrentTimedRotatingFileHandler appends numbers instead of just increment

### ISSUE THREAD

**Issue by moynihan** [Preston-Landers/concurrent-log-handler#68]
https://github.com/Preston-Landers/concurrent-log-handler/blob/8951164a7153f95add5ed62d18946752e3de012b/src/concurrent_log_handler/__init__.py#L822-L828

I think this not the logic you intended for it to be, it appends a new number to the file name making it grow in length.  the `ConcurrentRotatingFileHandler` seems do work as expected, but the `ConcurrentTimedRotatingFileHandler` does not

Example
```
mylog.log
mylog.log.2023-11-28_16.1.2.3.4.5.6.7.8.9.10.gz
mylog.log.2023-11-28_16.1.2.3.4.5.6.7.8.9.gz
mylog.log.2023-11-28_16.1.2.3.4.5.6.7.8.gz
mylog.log.2023-11-28_16.1.2.3.4.5.6.7.gz
mylog.log.2023-11-28_16.1.2.3.4.5.6.gz
mylog.log.2023-11-28_16.1.2.3.4.5.gz
mylog.log.2023-11-28_16.1.2.3.4.gz
mylog.log.2023-11-28_16.1.2.3.gz
mylog.log.2023-11-28_16.1.2.gz
mylog.log.2023-11-28_16.1.gz
mylog.log.2023-11-28_16.gz
```

If you update it to something like this 
```python 
counter = 1
if os.path.exists(dfn + gzip_ext):
    while os.path.exists(f'{dfn}.{counter}{gzip_ext}'):
        ending = f".{counter - 1}{gzip_ext}"
        if dfn.endswith(ending):
            dfn = dfn[: -len(ending)]
        counter += 1
    dfn = f"{dfn}.{counter}"
```
Then it will output increment the last digit only

Example:
```
mylog.log
mylog.log.2023-11-28_16.gz
mylog.log.2023-11-28_16.1.gz
mylog.log.2023-11-28_16.2.gz
mylog.log.2023-11-28_16.3.gz
mylog.log.2023-11-28_16.4.gz
mylog.log.2023-11-28_16.5.gz
mylog.log.2023-11-28_16.6.gz
mylog.log.2023-11-28_16.7.gz
mylog.log.2023-11-28_16.8.gz
mylog.log.2023-11-28_16.9.gz
mylog.log.2023-11-28_16.10.gz
```

**Comment by Preston-Landers** [comment]
OK looks like this should hopefully be fixed in the latest version in master branch. The unit tests have been updated to look for this condition. Also needed a special fix for Python 3.8 and earlier because the base class method didn't support additional suffixes like `.1`.

Thanks so much for the testing and the code fix!

**Comment by moynihan** [comment]
I was using python 3.9.15.  Thanks for actively developing this, i'm looking forward to using it

**Comment by moynihan** [comment]
Any idea when these will make it to pypi?

**Comment by Preston-Landers** [comment]
I will do it this week for sure. Thanks.

**Comment by Preston-Landers** [comment]
@moynihan It's been uploaded to pypi now. Thanks for your patience!
