### ISSUE TITLE
python27 has no function rotation_filename 

### ISSUE THREAD

**Issue by wlxklyh** [Preston-Landers/concurrent-log-handler#72]
__init__.py line 558 559 570 use function rotation_filename not find in python27 BaseRotatingHandler

**Comment by Preston-Landers** [comment]
For Python 2.7 support you might try release 0.9.20. I think the Readme says 0.9.22 works with Python 2.7 but it might be wrong. Otherwise, this old version of Python is not supported going forward for this project. Thanks.

**Comment by wlxklyh** [comment]
Thank you for your reply.
