### ISSUE TITLE
The .tar.gz distribution isn't installable

### ISSUE THREAD

**Issue by Preston-Landers** [Preston-Landers/concurrent-log-handler#75]
@SukeerthiBJ notes here:
https://github.com/Preston-Landers/concurrent-log-handler/pull/67#issuecomment-2337062013
That the .tar.gz release doesn't seem to include the setup.py script, making it difficult to install normally. 

On the [release page here](https://github.com/Preston-Landers/concurrent-log-handler/releases/tag/0.9.25) there's two .tar.gz files - I think one is auto-generated - but neither seems to include setup.py / setup.cfg.

**Comment by SukeerthiBJ** [comment]
@Preston-Landers , is there a way to get these two files for this tar. For our internal python package creation this step is failing due to absence of these files

**Comment by Preston-Landers** [comment]
Actually I forgot about [earlier changes](https://github.com/Preston-Landers/concurrent-log-handler/commit/6fb63e67cd91d992458185813f9e63d18a67e91b) that got rid of the setup.py file.

Instead, you're supposed to use the pyproject.toml file. E.g. with Pip you can download the tar.gz and cd into it and run `pip install .`
